### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by ank1traj** [kiranonline/Online-Examination-System#1]
How to login??

**Comment by 224alpha** [comment]
Steps------
After cloning the project
1.  the frontend folder is just in case you want to see the code, it's already built and integrated with the backend . so all the steps will be in backend folder only.
2. Go to config folder, open default.json and make required changes(put a MongoDB connection string and a jwt secret and SMTP server credentials for Gmail)
3. Go to tools file inside the services folder and make changes in the createadmin function(name, email, password, contact) (** Don't change type)
4. This tool file is already imported in app.js, just invoke the createadmin function once, and run the server.
5. Once you get admin created in the database. Delete the createadmin function invocation, otherwise, it will again create another admin account.
6. Now you can log in to the portal using admin account and you can create accounts for trainers.

**Comment by ank1traj** [comment]
> Steps------
> After cloning the project
> 
> 1. the frontend folder is just in case you want to see the code, it's already built and integrated with the backend . so all the steps will be in backend folder only.
> 2. Go to config folder, open default.json and make required changes(put a MongoDB connection string and a jwt secret and SMTP server credentials for Gmail)
> 3. Go to tools file inside the services folder and make changes in the createadmin function(name, email, password, contact) (** Don't change type)
> 4. This tool file is already imported in app.js, just invoke the createadmin function once, and run the server.
> 5. Once you get admin created in the database. Delete the createadmin function invocation, otherwise, it will again create another admin account.
> 6. Now you can log in to the portal using admin account and you can create accounts for trainers.

Is it compulsory to change JWT?

**Comment by 224alpha** [comment]
put any random word as jwt secret. having a jwt secret secures your jwt token.

**Comment by ank1traj** [comment]
I did all the above steps but still I am getting error.

**Comment by 224alpha** [comment]
can you put an image of the error?

**Comment by 224alpha** [comment]
Make sure to install all the dependencies before doing anything inside the backend folder.

**Comment by ank1traj** [comment]
![13](https://user-images.githubusercontent.com/32160084/67386892-6e4cf880-f5b3-11e9-890c-2ee66e9adde7.png)

![12](https://user-images.githubusercontent.com/32160084/67387032-afdda380-f5b3-11e9-848d-f093c286d485.png)
![14](https://user-images.githubusercontent.com/32160084/67387204-09de6900-f5b4-11e9-9365-75c0a8e20667.png)


This is the changes I made in tool.js, default.json and app.js

**Comment by 224alpha** [comment]
There is no error in the createadmin function. seems that your editor is not able to identify arrow function or your node version is old.

**Comment by 224alpha** [comment]
put your password ankitraj in double quote

**Comment by team-umeed** [comment]
The user is being created yet it is not allowing login. What should I do?
